name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up Python (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        python3 -m pip install --user setuptools

    - name: Install dependencies
      run: npm ci
      timeout-minutes: 10

    - name: Build application (macOS x64)
      if: matrix.os == 'macos-latest'
      run: npm run build -- --mac --x64
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
      timeout-minutes: 30

    - name: Build application (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}
      timeout-minutes: 30

    - name: Upload Windows artifacts
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/*.exe

    - name: Upload macOS artifacts
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist/*.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: List files
      run: |
        find dist -type f

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN || secrets.GITHUB_TOKEN }}